package uz.pdp.rentseekerlongpolling.service;

import uz.pdp.rentseekerlongpolling.util.constant.Constant;
import uz.pdp.rentseekerlongpolling.util.enums.District;
import uz.pdp.rentseekerlongpolling.util.enums.Language;
import uz.pdp.rentseekerlongpolling.util.enums.Region;


public class LanguageService implements Constant {

    public static String getWord(String word, Language language) {
        switch (language) {
            case UZ:
                return getUzWord(word);
            case RU:
                return getRuWord(word);
            case EN:
                return getEnWord(word);
        }
        return ERROR;
    }

    private static String getUzWord(String word) {
        switch (word) {
            case UZ:
                return UZ;
            case RU:
                return RU;
            case EN:
                return EN;

            case ADMIN_USERS_SHOW_MENU_TEXT:
                return ADMIN_USERS_SHOW_MENU_TEXT_UZ;
            case ADMIN_CHOOSE_USERS_MENU_TEXT:
                return ADMIN_CHOOSE_USERS_MENU_TEXT_UZ;
            case ADMIN_ENTER_PHONE_NUMBER_MENU_TEXT:
                return ADMIN_ENTER_PHONE_NUMBER_MENU_TEXT_UZ;
            case ADMIN_SHOW_USERS:
                return ADMIN_SHOW_USERS_UZ;
            case ADMIN_SHOW_HOMES:
                return ADMIN_SHOW_HOMES_UZ;
            case ADMIN_EXCEL_FILE:
                return ADMIN_EXCEL_FILE_UZ;
            case ADMIN_ACTIVE_USERS:
                return ADMIN_ACTIVE_USERS_UZ;
            case ADMIN_DEACTIVATED_USERS:
                return ADMIN_DEACTIVATED_USERS_UZ;
            case ADMIN_USER_INFO_PHONE_NUMBER:
                return ADMIN_USER_INFO_PHONE_NUMBER_UZ;
            case ADMIN_USER_INFO_NAME:
                return ADMIN_USER_INFO_NAME_UZ;
            case ADMIN_USER_INFO_LANGUAGE:
                return ADMIN_USER_INFO_LANGUAGE_UZ;
            case ADMIN_HOMES_IN_WEEK:
                return ADMIN_HOMES_IN_WEEK_UZ;
            case ADMIN_HOMES_IN_DAY:
                return ADMIN_HOMES_IN_DAY_UZ;
            case ADMIN_HOMES_INFO_HOME_TYPE:
                return ADMIN_HOMES_INFO_HOME_TYPE_UZ;
            case ADMIN_HOMES_INFO_REGION:
                return ADMIN_HOMES_INFO_REGION_UZ;
            case ADMIN_HOMES_INFO_DISTRICT:
                return ADMIN_HOMES_INFO_DISTRICT_UZ;
            case ADMIN_HOMES_INFO_ADDRESS:
                return ADMIN_HOMES_INFO_ADDRESS_UZ;
            case ADMIN_HOMES_INFO_NUMBER_OF_ROOMS:
                return ADMIN_HOMES_INFO_NUMBER_OF_ROOMS_UZ;
            case ADMIN_HOMES_INFO_AREA:
                return ADMIN_HOMES_INFO_AREA_UZ;
            case ADMIN_HOMES_INFO_DESCRIPTION:
                return ADMIN_HOMES_INFO_DESCRIPTION_UZ;
            case ADMIN_HOMES_INFO_NUMBER_OF_INTERESTED:
                return ADMIN_HOMES_INFO_NUMBER_OF_INTERESTED_UZ;
            case ADMIN_HOMES_INFO_MAP_URL:
                return ADMIN_HOMES_INFO_MAP_URL_UZ;
            case ADMIN_HOMES_FILTER_MENU_TEXT:
                return ADMIN_HOMES_FILTER_MENU_TEXT_UZ;

            case CHOOSE_ACTION:
                return CHOOSE_ACTION_UZ;
            case CHOOSE_LANGUAGE_MENU_TEXT:
                return CHOOSE_LANGUAGE_MENU_TEXT_UZ;
            case CHOOSE_REGION_MENU_TEXT:
                return CHOOSE_REGION_MENU_TEXT_UZ;
            case SET_ACCOMMODATION_FOR_MENU_TEXT:
                return SET_ACCOMMODATION_FOR_MENU_TEXT_UZ;
            case CHOOSE_ACCOMMODATION_TYPE_MENU_TEXT:
                return CHOOSE_ACCOMMODATION_TYPE_MENU_TEXT_UZ;
            case ENTER_MAX_VALUE_MENU_TEXT:
                return ENTER_MAX_VALUE_MENU_TEXT_UZ;
            case ENTER_MIN_VALUE_MENU_TEXT:
                return ENTER_MIN_VALUE_MENU_TEXT_UZ;
            case ENTER_AREA_MENU_TEXT:
                return ENTER_AREA_MENU_TEXT_UZ;
            case SEND_PHOTO_MENU_TEXT:
                return SEND_PHOTO_MENU_TEXT_UZ;
            case ENTER_PRICE_MENU_TEXT:
                return ENTER_PRICE_MENU_TEXT_UZ;
            case WRITE_DESCRIPTION_MENU_TEXT:
                return WRITE_DESCRIPTION_MENU_TEXT_UZ;
            case CHANGE_LANGUAGE:
                return CHANGE_LANGUAGE_UZ;
            case WELCOME_TEXT:
                return WELCOME_TEXT_UZ;
            case SEARCH:
                return SEARCH_UZ;
            case BACK:
                return BACK_UZ;
            case FOR_RENTING:
                return FOR_RENTING_UZ;
            case FOR_SELLING:
                return FOR_SELLING_UZ;
            case WRITE_ADDRESS:
                return WRITE_ADDRESS_UZ;
            case SEND_LOCATION:
                return SEND_LOCATION_UZ;
            case HOUSE:
                return HOUSE_UZ;
            case FLAT:
                return FLAT_UZ;
            case NUMBER_OF_ROOMS:
                return NUMBER_OF_ROOMS_UZ;
            case AREA:
                return AREA_UZ;
            case SEND_PHOTOS:
                return SEND_PHOTOS_UZ;
            case DO_NOT_SEND_PHOTO:
                return DO_NOT_SEND_PHOTO_UZ;
            case SET_PRICE:
                return SET_PRICE_UZ;
            case WRITE_DESCRIPTION:
                return WRITE_DESCRIPTION_UZ;
            case HOUSE_TYPE:
                return HOUSE_TYPE_UZ;
            case ADDRESS:
                return ADDRESS_UZ;
            case DESCRIPTION:
                return DESCRIPTION_UZ;
            case DATE:
                return DATE_UZ;
            case NUMBER_OF_LIKES:
                return NUMBER_OF_LIKES_UZ;
            case NUMBER_OF_VIEWS:
                return NUMBER_OF_VIEWS_UZ;
            case GET_PHONE_NUMBER:
                return GET_PHONE_NUMBER_UZ;
            case MY_ACCOMMODATIONS:
                return MY_ACCOMMODATIONS_UZ;
            case MY_FAVOURITES:
                return MY_FAVOURITES_UZ;
            case SEARCH_BY_ROOMS:
                return SEARCH_BY_ROOMS_UZ;
            case SEARCH_BY_PRICE:
                return SEARCH_BY_PRICE_UZ;
            case MAX_PRICE:
                return MAX_PRICE_UZ;
            case MIN_PRICE:
                return MIN_PRICE_UZ;
            case MAX_ROOMS:
                return MAX_ROOMS_UZ;
            case MIN_ROOMS:
                return MIN_ROOMS_UZ;
            case ENTER_PHONE_NUMBER_TEXT:
                return ENTER_PHONE_NUMBER_TEXT_UZ;
            case SEND_PHONE_NUMBER:
                return SEND_PHONE_NUMBER_UZ;
            case CHANGE_LANGUAGE_TEXT:
                return CHANGE_LANGUAGE_TEXT_UZ;
            case ADD_ACCOMMODATION:
                return ADD_ACCOMMODATION_UZ;
            case SHOW_ACCOMMODATIONS:
                return SHOW_ACCOMMODATIONS_UZ;
            case MY_NOTES:
                return MY_NOTES_UZ;
            case SETTINGS:
                return SETTINGS_UZ;
            case MENU_TEXT:
                return MENU_TEXT_UZ;
            case REGISTRATION:
                return REGISTRATION_UZ;
            case CHOOSE_ONE:
                return CHOOSE_ONE_UZ;
            case MY_PHONE_NUMBER:
                return MY_PHONE_NUMBER_UZ;
            case REGISTER_WARNING_TEXT:
                return REGISTER_WARNING_TEXT_UZ;
            case WRITE_SEND_LOCATION_TEXT:
                return WRITE_SEND_LOCATION_TEXT_UZ;
            case SEND_LOCATION_TEXT:
                return SEND_LOCATION_TEXT_UZ;
            case LOCATION_NOT_FOUND:
                return LOCATION_NOT_FOUND_UZ;
            case ADMIN_HOMES_INFO_PRICE:
                return ADMIN_HOMES_INFO_PRICE_UZ;
            case HOMES_NOT_FOUND:
                return HOMES_NOT_FOUND_UZ;
            case GET_RENTING:
                return GET_RENTING_UZ;
            case FOR_BUY:
                return FOR_BUY_UZ;
            case SKIP:
                return SKIP_UZ;
            case STATUS:
                return STATUS_UZ;
            case RENT:
                return RENT_UZ;
            case SELL:
                return SELL_UZ;
            case MENU:
                return MENU_UZ;
            case ADMIN:
                return ADMIN_UZ;
            case USER:
                return USER_UZ;
            case CHOOSE_DISTRICT_MENU_TEXT:
                return CHOOSE_DISTRICT_MENU_TEXT_UZ;
            case SUCCESSFULLY_SAVED:
                return SUCCESSFULLY_SAVED_UZ;
            case SHOW_ALL:
                return SHOW_ALL_UZ;
            case ADMIN_USER_INFO_USERNAME:
                return ADMIN_USER_INFO_USERNAME_UZ;
            case ROLE:
                return ROLE_UZ;
            case SITUATION:
                return SITUATION_UZ;
            case ACTIVE:
                return ACTIVE_UZ;
            case DE_ACTIVE:
                return DE_ACTIVE_UZ;
            case CHECK_USER_BY_ADMIN_TEXT:
                return CHECK_USER_BY_ADMIN_TEXT_UZ;
            case BAN_MENU_TEXT:return BAN_MENU_TEXT_UZ;
            case NEXT_ACTION:return NEXT_ACTION_UZ;
            case HOME_PHOTOS:return HOME_PHOTOS_UZ;
            case IT_HAS_ONLY_ONE_PIC:return IT_HAS_ONLY_ONE_PIC_UZ;
            case FIRST_PAGE_NOTIFICATION:return FIRST_PAGE_NOTIFICATION_UZ;
            case LAST_PAGE_NOTIFICATION:return LAST_PAGE_NOTIFICATION_UZ;


            case TASHKENT:
                return Region.TASHKENT.getUz();
            case TASHKENT_REGION:
                return Region.TASHKENT_REGION.getUz();
            case ANDIJAN:
                return Region.ANDIJAN.getUz();
            case BUKHARA:
                return Region.BUKHARA.getUz();
            case DZHIZAK:
                return Region.DZHIZAK.getUz();
            case KASHKADARYA:
                return Region.KASHKADARYA.getUz();
            case NAVOI:
                return Region.NAVOI.getUz();
            case NAMANGAN:
                return Region.NAMANGAN.getUz();
            case SAMARKAND:
                return Region.SAMARKAND.getUz();
            case SURKHANDARYA:
                return Region.SURKHANDARYA.getUz();
            case SYRDARYA:
                return Region.SYRDARYA.getUz();
            case FERGHANA:
                return Region.FERGHANA.getUz();
            case XORAZM:
                return Region.XORAZM.getUz();
            case REPUBLIC_OF_KARAKALPAKSTAN:
                return Region.REPUBLIC_OF_KARAKALPAKSTAN.getUz();

            case OLMAZOR:
                return District.OLMAZOR.getUz();
            case BEKTEMIR:
                return District.BEKTEMIR.getUz();
            case MIROBOD:
                return District.MIROBOD.getUz();
            case MIRZO_ULUGBEK:
                return District.MIRZO_ULUGBEK.getUz();
            case SERGELI:
                return District.SERGELI.getUz();
            case UCHTEPA:
                return District.UCHTEPA.getUz();
            case SHAYXONTOHUR:
                return District.SHAYXONTOHUR.getUz();
            case YASHNOBOD:
                return District.YASHNOBOD.getUz();
            case CHILONZOR:
                return District.CHILONZOR.getUz();
            case YUNUSOBOD:
                return District.YUNUSOBOD.getUz();
            case YAKKASAROY:
                return District.YAKKASAROY.getUz();
            case BEKOBOD:
                return District.BEKOBOD.getUz();
            case BOSTONLIQ:
                return District.BOSTONLIQ.getUz();
            case BOKA:
                return District.BOKA.getUz();
            case CHINOZ:
                return District.CHINOZ.getUz();
            case QIBRAY:
                return District.QIBRAY.getUz();
            case OHANGARON:
                return District.OHANGARON.getUz();
            case OQQORGON:
                return District.OQQORGON.getUz();
            case PARKENT:
                return District.PARKENT.getUz();
            case PISKENT:
                return District.PISKENT.getUz();
            case QUYI_CHIRCHIQ:
                return District.QUYI_CHIRCHIQ.getUz();
            case ZANGIOTA:
                return District.ZANGIOTA.getUz();
            case ORTA_CHIRCHIQ:
                return District.ORTA_CHIRCHIQ.getUz();
            case YANGIYOL:
                return District.YANGIYOL.getUz();
            case YUQORI_CHIRCHIQ:
                return District.YUQORI_CHIRCHIQ.getUz();
            case SHAHRIXON:
                return District.SHAHRIXON.getUz();
            case ASAKA:
                return District.ASAKA.getUz();
            case QORGONTEPA:
                return District.QORGONTEPA.getUz();
            case ANDIJON:
                return District.ANDIJON.getUz();
            case BALIQCHI:
                return District.BALIQCHI.getUz();
            case OLTINKOL:
                return District.OLTINKOL.getUz();
            case JALAQUDUQ:
                return District.JALAQUDUQ.getUz();
            case IZBOSKAN:
                return District.IZBOSKAN.getUz();
            case PAXTAOBOD:
                return District.PAXTAOBOD.getUz();
            case MARHAMAT:
                return District.MARHAMAT.getUz();
            case XOJAOBOD:
                return District.XOJAOBOD.getUz();
            case BULOQBOSHI:
                return District.BULOQBOSHI.getUz();
            case BOSTON:
                return District.BOSTON.getUz();
            case ULUGNOR:
                return District.ULUGNOR.getUz();
            case XONOBOD:
                return District.XONOBOD.getUz();
            case BUXORO:
                return District.BUXORO.getUz();
            case GIJDUVON:
                return District.GIJDUVON.getUz();
            case JONDOR:
                return District.JONDOR.getUz();
            case KOGON:
                return District.KOGON.getUz();
            case OLOT:
                return District.OLOT.getUz();
            case PESHKU:
                return District.PESHKU.getUz();
            case QORAKOL:
                return District.QORAKOL.getUz();
            case QOROVULBOZOR:
                return District.QOROVULBOZOR.getUz();
            case ROMITAN:
                return District.ROMITAN.getUz();
            case SHOFIRKON:
                return District.SHOFIRKON.getUz();
            case VOBKENT:
                return District.VOBKENT.getUz();
            case ARNASOY:
                return District.ARNASOY.getUz();
            case BAXMAL:
                return District.BAXMAL.getUz();
            case DOSTLIK:
                return District.DOSTLIK.getUz();
            case FORISH:
                return District.FORISH.getUz();
            case GALLAOROL:
                return District.GALLAOROL.getUz();
            case JIZZAX:
                return District.JIZZAX.getUz();
            case MIRZACHOL:
                return District.MIRZACHOL.getUz();
            case PAXTAKOR:
                return District.PAXTAKOR.getUz();
            case YANGIOBOD:
                return District.YANGIOBOD.getUz();
            case ZAFAROBOD:
                return District.ZAFAROBOD.getUz();
            case ZARBAND:
                return District.ZARBAND.getUz();
            case ZOMIN:
                return District.ZOMIN.getUz();
            case CHIROQCHI:
                return District.CHIROQCHI.getUz();
            case DEHQONOBOD:
                return District.DEHQONOBOD.getUz();
            case GUZOR:
                return District.GUZOR.getUz();
            case KASBI:
                return District.KASBI.getUz();
            case KITOB:
                return District.KITOB.getUz();
            case KOSON:
                return District.KOSON.getUz();
            case MIRISHKOR:
                return District.MIRISHKOR.getUz();
            case MUBORAK:
                return District.MUBORAK.getUz();
            case NISHON:
                return District.NISHON.getUz();
            case QAMASHI:
                return District.QAMASHI.getUz();
            case QARSHI:
                return District.QARSHI.getUz();
            case SHAHRISABZ:
                return District.SHAHRISABZ.getUz();
            case YAKKABOG:
                return District.YAKKABOG.getUz();
            case KARMANA:
                return District.KARMANA.getUz();
            case KONIMEX:
                return District.KONIMEX.getUz();
            case NAVBAHOR:
                return District.NAVBAHOR.getUz();
            case NUROTA:
                return District.NUROTA.getUz();
            case QIZILTEPA:
                return District.QIZILTEPA.getUz();
            case TOMDI:
                return District.TOMDI.getUz();
            case UCHQUDUQ:
                return District.UCHQUDUQ.getUz();
            case XATIRCHI:
                return District.XATIRCHI.getUz();
            case CHORTOQ:
                return District.CHORTOQ.getUz();
            case CHUST:
                return District.CHUST.getUz();
            case KOSONSOY:
                return District.KOSONSOY.getUz();
            case MINGBULOQ:
                return District.MINGBULOQ.getUz();
            case NAMANGON:
                return District.NAMANGON.getUz();
            case NORIN:
                return District.NORIN.getUz();
            case POP:
                return District.POP.getUz();
            case TORAQORGON:
                return District.TORAQORGON.getUz();
            case UCHQORGON:
                return District.UCHQORGON.getUz();
            case UYCHI:
                return District.UYCHI.getUz();
            case YANGIQORGON:
                return District.YANGIQORGON.getUz();
            case BULUNGUR:
                return District.BULUNGUR.getUz();
            case ISHTIXON:
                return District.ISHTIXON.getUz();
            case JOMBOY:
                return District.JOMBOY.getUz();
            case KATTAQORGON:
                return District.KATTAQORGON.getUz();
            case NARPAY:
                return District.NARPAY.getUz();
            case NUROBOD:
                return District.NUROBOD.getUz();
            case OQDARYO:
                return District.OQDARYO.getUz();
            case PAST_DARGOM:
                return District.PAST_DARGOM.getUz();
            case PAXTACHI:
                return District.PAXTACHI.getUz();
            case POYARIQ:
                return District.POYARIQ.getUz();
            case QOSHRABOT:
                return District.QOSHRABOT.getUz();
            case SAMARQAND:
                return District.SAMARQAND.getUz();
            case TOYLOQ:
                return District.TOYLOQ.getUz();
            case URGUT:
                return District.URGUT.getUz();
            case ANGOR:
                return District.ANGOR.getUz();
            case BANDIXON:
                return District.BANDIXON.getUz();
            case BOYSUN:
                return District.BOYSUN.getUz();
            case DENOV:
                return District.DENOV.getUz();
            case JARQORGON:
                return District.JARQORGON.getUz();
            case MUZROBOR:
                return District.MUZROBOR.getUz();
            case OLTINSOY:
                return District.OLTINSOY.getUz();
            case QIZIRIQ:
                return District.QIZIRIQ.getUz();
            case QUMQORGON:
                return District.QUMQORGON.getUz();
            case SARIOSIYO:
                return District.SARIOSIYO.getUz();
            case SHEROBOD:
                return District.SHEROBOD.getUz();
            case SHORCHI:
                return District.SHORCHI.getUz();
            case TERMIZ:
                return District.TERMIZ.getUz();
            case UZUN:
                return District.UZUN.getUz();
            case BOYOVUT:
                return District.BOYOVUT.getUz();
            case GULISTON:
                return District.GULISTON.getUz();
            case OQOLTIN:
                return District.OQOLTIN.getUz();
            case SARDOBA:
                return District.SARDOBA.getUz();
            case SAYXUNOBOD:
                return District.SAYXUNOBOD.getUz();
            case SIRDARYO:
                return District.SIRDARYO.getUz();
            case XOVOS:
                return District.XOVOS.getUz();
            case MIRZAOBOD:
                return District.MIRZAOBOD.getUz();
            case BESHARIQ:
                return District.BESHARIQ.getUz();
            case BOGDOD:
                return District.BOGDOD.getUz();
            case BUVAYDA:
                return District.BUVAYDA.getUz();
            case DANGARA:
                return District.DANGARA.getUz();
            case FARGONA:
                return District.FARGONA.getUz();
            case FURQAT:
                return District.FURQAT.getUz();
            case OZBEKISTON:
                return District.OZBEKISTON.getUz();
            case OLTIARIQ:
                return District.OLTIARIQ.getUz();
            case QOSHTEPA:
                return District.QOSHTEPA.getUz();
            case QUVA:
                return District.QUVA.getUz();
            case RISHTON:
                return District.RISHTON.getUz();
            case SOX:
                return District.SOX.getUz();
            case TOSHLOQ:
                return District.TOSHLOQ.getUz();
            case UCHKOPRIK:
                return District.UCHKOPRIK.getUz();
            case YOZYOVON:
                return District.YOZYOVON.getUz();
            case BOGOT:
                return District.BOGOT.getUz();
            case GURLAN:
                return District.GURLAN.getUz();
            case QOSHKOPIR:
                return District.QOSHKOPIR.getUz();
            case SHOVOT:
                return District.SHOVOT.getUz();
            case URGANCH:
                return District.URGANCH.getUz();
            case XAZORASP:
                return District.XAZORASP.getUz();
            case XIVA:
                return District.XIVA.getUz();
            case XONQA:
                return District.XONQA.getUz();
            case YANGIARIQ:
                return District.YANGIARIQ.getUz();
            case YANGIBOZOR:
                return District.YANGIBOZOR.getUz();
            case AMUDARYO:
                return District.AMUDARYO.getUz();
            case BERUNIY:
                return District.BERUNIY.getUz();
            case CHIMBOY:
                return District.CHIMBOY.getUz();
            case ELLIKQALA:
                return District.ELLIKQALA.getUz();
            case KEGEYLI:
                return District.KEGEYLI.getUz();
            case MOYNOQ:
                return District.MOYNOQ.getUz();
            case NUKUS:
                return District.NUKUS.getUz();
            case QONLIKOL:
                return District.QONLIKOL.getUz();
            case QORAUZAQ:
                return District.QORAUZAQ.getUz();
            case QUNGIROT:
                return District.QUNGIROT.getUz();
            case SHUMANAY:
                return District.SHUMANAY.getUz();
            case TAXTAKOPIR:
                return District.TAXTAKOPIR.getUz();
            case TORTKOL:
                return District.TORTKOL.getUz();
            case XOJAYLI:
                return District.XOJAYLI.getUz();

        }
        return ERROR;
    }

    private static String getRuWord(String word) {
        switch (word) {
            case UZ:
                return UZ;
            case RU:
                return RU;
            case EN:
                return EN;

            case ADMIN_USERS_SHOW_MENU_TEXT:
                return ADMIN_USERS_SHOW_MENU_TEXT_RU;
            case ADMIN_CHOOSE_USERS_MENU_TEXT:
                return ADMIN_CHOOSE_USERS_MENU_TEXT_RU;
            case ADMIN_ENTER_PHONE_NUMBER_MENU_TEXT:
                return ADMIN_ENTER_PHONE_NUMBER_MENU_TEXT_RU;
            case ADMIN_SHOW_USERS:
                return ADMIN_SHOW_USERS_RU;
            case ADMIN_SHOW_HOMES:
                return ADMIN_SHOW_HOMES_RU;
            case ADMIN_EXCEL_FILE:
                return ADMIN_EXCEL_FILE_RU;
            case ADMIN_ACTIVE_USERS:
                return ADMIN_ACTIVE_USERS_RU;
            case ADMIN_DEACTIVATED_USERS:
                return ADMIN_DEACTIVATED_USERS_RU;
            case ADMIN_USER_INFO_PHONE_NUMBER:
                return ADMIN_USER_INFO_PHONE_NUMBER_RU;
            case ADMIN_USER_INFO_NAME:
                return ADMIN_USER_INFO_NAME_RU;
            case ADMIN_USER_INFO_LANGUAGE:
                return ADMIN_USER_INFO_LANGUAGE_RU;
            case ADMIN_HOMES_IN_WEEK:
                return ADMIN_HOMES_IN_WEEK_RU;
            case ADMIN_HOMES_IN_DAY:
                return ADMIN_HOMES_IN_DAY_RU;
            case ADMIN_HOMES_INFO_HOME_TYPE:
                return ADMIN_HOMES_INFO_HOME_TYPE_RU;
            case ADMIN_HOMES_INFO_REGION:
                return ADMIN_HOMES_INFO_REGION_RU;
            case ADMIN_HOMES_INFO_DISTRICT:
                return ADMIN_HOMES_INFO_DISTRICT_RU;
            case ADMIN_HOMES_INFO_ADDRESS:
                return ADMIN_HOMES_INFO_ADDRESS_RU;
            case ADMIN_HOMES_INFO_NUMBER_OF_ROOMS:
                return ADMIN_HOMES_INFO_NUMBER_OF_ROOMS_RU;
            case ADMIN_HOMES_INFO_AREA:
                return ADMIN_HOMES_INFO_AREA_RU;
            case ADMIN_HOMES_INFO_DESCRIPTION:
                return ADMIN_HOMES_INFO_DESCRIPTION_RU;
            case ADMIN_HOMES_INFO_NUMBER_OF_INTERESTED:
                return ADMIN_HOMES_INFO_NUMBER_OF_INTERESTED_RU;
            case ADMIN_HOMES_INFO_MAP_URL:
                return ADMIN_HOMES_INFO_MAP_URL_RU;
            case ADMIN_HOMES_FILTER_MENU_TEXT:
                return ADMIN_HOMES_FILTER_MENU_TEXT_RU;


            case CHOOSE_ACTION:
                return CHOOSE_ACTION_RU;
            case CHOOSE_LANGUAGE_MENU_TEXT:
                return CHOOSE_LANGUAGE_MENU_TEXT_RU;
            case CHOOSE_REGION_MENU_TEXT:
                return CHOOSE_REGION_MENU_TEXT_RU;
            case SET_ACCOMMODATION_FOR_MENU_TEXT:
                return SET_ACCOMMODATION_FOR_MENU_TEXT_RU;
            case CHOOSE_ACCOMMODATION_TYPE_MENU_TEXT:
                return CHOOSE_ACCOMMODATION_TYPE_MENU_TEXT_RU;
            case ENTER_MAX_VALUE_MENU_TEXT:
                return ENTER_MAX_VALUE_MENU_TEXT_RU;
            case ENTER_MIN_VALUE_MENU_TEXT:
                return ENTER_MIN_VALUE_MENU_TEXT_RU;
            case ENTER_AREA_MENU_TEXT:
                return ENTER_AREA_MENU_TEXT_RU;
            case SEND_PHOTO_MENU_TEXT:
                return SEND_PHOTO_MENU_TEXT_RU;
            case ENTER_PRICE_MENU_TEXT:
                return ENTER_PRICE_MENU_TEXT_RU;
            case WRITE_DESCRIPTION_MENU_TEXT:
                return WRITE_DESCRIPTION_MENU_TEXT_RU;
            case CHANGE_LANGUAGE:
                return CHANGE_LANGUAGE_RU;
            case WELCOME_TEXT:
                return WELCOME_TEXT_RU;
            case SEARCH:
                return SEARCH_RU;
            case BACK:
                return BACK_RU;
            case FOR_RENTING:
                return FOR_RENTING_RU;
            case FOR_SELLING:
                return FOR_SELLING_RU;
            case WRITE_ADDRESS:
                return WRITE_ADDRESS_RU;
            case SEND_LOCATION:
                return SEND_LOCATION_RU;
            case HOUSE:
                return HOUSE_RU;
            case FLAT:
                return FLAT_RU;
            case NUMBER_OF_ROOMS:
                return NUMBER_OF_ROOMS_RU;
            case AREA:
                return AREA_RU;
            case SEND_PHOTOS:
                return SEND_PHOTOS_RU;
            case DO_NOT_SEND_PHOTO:
                return DO_NOT_SEND_PHOTO_RU;
            case SET_PRICE:
                return SET_PRICE_RU;
            case WRITE_DESCRIPTION:
                return WRITE_DESCRIPTION_RU;
            case HOUSE_TYPE:
                return HOUSE_TYPE_RU;
            case ADDRESS:
                return ADDRESS_RU;
            case DESCRIPTION:
                return DESCRIPTION_RU;
            case DATE:
                return DATE_RU;
            case NUMBER_OF_LIKES:
                return NUMBER_OF_LIKES_RU;
            case NUMBER_OF_VIEWS:
                return NUMBER_OF_VIEWS_RU;
            case GET_PHONE_NUMBER:
                return GET_PHONE_NUMBER_RU;
            case MY_ACCOMMODATIONS:
                return MY_ACCOMMODATIONS_RU;
            case MY_FAVOURITES:
                return MY_FAVOURITES_RU;
            case SEARCH_BY_ROOMS:
                return SEARCH_BY_ROOMS_RU;
            case SEARCH_BY_PRICE:
                return SEARCH_BY_PRICE_RU;
            case MAX_PRICE:
                return MAX_PRICE_RU;
            case MIN_PRICE:
                return MIN_PRICE_RU;
            case MAX_ROOMS:
                return MAX_ROOMS_RU;
            case MIN_ROOMS:
                return MIN_ROOMS_RU;
            case ENTER_PHONE_NUMBER_TEXT:
                return ENTER_PHONE_NUMBER_TEXT_RU;
            case SEND_PHONE_NUMBER:
                return SEND_PHONE_NUMBER_RU;
            case CHANGE_LANGUAGE_TEXT:
                return CHANGE_LANGUAGE_TEXT_RU;
            case ADD_ACCOMMODATION:
                return ADD_ACCOMMODATION_RU;
            case SHOW_ACCOMMODATIONS:
                return SHOW_ACCOMMODATIONS_RU;
            case MY_NOTES:
                return MY_NOTES_RU;
            case SETTINGS:
                return SETTINGS_RU;
            case MENU_TEXT:
                return MENU_TEXT_RU;
            case REGISTRATION:
                return REGISTRATION_RU;
            case CHOOSE_ONE:
                return CHOOSE_ONE_RU;
            case MY_PHONE_NUMBER:
                return MY_PHONE_NUMBER_RU;
            case REGISTER_WARNING_TEXT:
                return REGISTER_WARNING_TEXT_RU;
            case WRITE_SEND_LOCATION_TEXT:
                return WRITE_SEND_LOCATION_TEXT_RU;
            case SEND_LOCATION_TEXT:
                return SEND_LOCATION_TEXT_RU;
            case LOCATION_NOT_FOUND:
                return LOCATION_NOT_FOUND_RU;
            case ADMIN_HOMES_INFO_PRICE:
                return ADMIN_HOMES_INFO_PRICE_RU;
            case HOMES_NOT_FOUND:
                return HOMES_NOT_FOUND_RU;
            case GET_RENTING:
                return GET_RENTING_RU;
            case FOR_BUY:
                return FOR_BUY_RU;
            case SKIP:
                return SKIP_RU;
            case STATUS:
                return STATUS_RU;
            case RENT:
                return RENT_RU;
            case SELL:
                return SELL_RU;
            case MENU:
                return MENU_RU;
            case ADMIN:
                return ADMIN_RU;
            case USER:
                return USER_RU;
            case CHOOSE_DISTRICT_MENU_TEXT:
                return CHOOSE_DISTRICT_MENU_TEXT_RU;
            case SUCCESSFULLY_SAVED:
                return SUCCESSFULLY_SAVED_RU;
            case SHOW_ALL:
                return SHOW_ALL_RU;
            case ADMIN_USER_INFO_USERNAME:
                return ADMIN_USER_INFO_USERNAME_RU;
            case ROLE:
                return ROLE_RU;
            case SITUATION:
                return SITUATION_RU;
            case ACTIVE:
                return ACTIVE_RU;
            case DE_ACTIVE:
                return DE_ACTIVE_RU;
            case CHECK_USER_BY_ADMIN_TEXT:
                return CHECK_USER_BY_ADMIN_TEXT_RU;
            case BAN_MENU_TEXT:return BAN_MENU_TEXT_RU;
            case NEXT_ACTION:return NEXT_ACTION_RU;
            case HOME_PHOTOS:return HOME_PHOTOS_RU;
            case IT_HAS_ONLY_ONE_PIC:return IT_HAS_ONLY_ONE_PIC_RU;

            case FIRST_PAGE_NOTIFICATION:return FIRST_PAGE_NOTIFICATION_RU;
            case LAST_PAGE_NOTIFICATION:return LAST_PAGE_NOTIFICATION_RU;


            case TASHKENT:
                return Region.TASHKENT.getRu();
            case TASHKENT_REGION:
                return Region.TASHKENT_REGION.getRu();
            case ANDIJAN:
                return Region.ANDIJAN.getRu();
            case BUKHARA:
                return Region.BUKHARA.getRu();
            case DZHIZAK:
                return Region.DZHIZAK.getRu();
            case KASHKADARYA:
                return Region.KASHKADARYA.getRu();
            case NAVOI:
                return Region.NAVOI.getRu();
            case NAMANGAN:
                return Region.NAMANGAN.getRu();
            case SAMARKAND:
                return Region.SAMARKAND.getRu();
            case SURKHANDARYA:
                return Region.SURKHANDARYA.getRu();
            case SYRDARYA:
                return Region.SYRDARYA.getRu();
            case FERGHANA:
                return Region.FERGHANA.getRu();
            case XORAZM:
                return Region.XORAZM.getRu();
            case REPUBLIC_OF_KARAKALPAKSTAN:
                return Region.REPUBLIC_OF_KARAKALPAKSTAN.getRu();

            case OLMAZOR:
                return District.OLMAZOR.getRu();
            case BEKTEMIR:
                return District.BEKTEMIR.getRu();
            case MIROBOD:
                return District.MIROBOD.getRu();
            case MIRZO_ULUGBEK:
                return District.MIRZO_ULUGBEK.getRu();
            case SERGELI:
                return District.SERGELI.getRu();
            case UCHTEPA:
                return District.UCHTEPA.getRu();
            case SHAYXONTOHUR:
                return District.SHAYXONTOHUR.getRu();
            case YASHNOBOD:
                return District.YASHNOBOD.getRu();
            case CHILONZOR:
                return District.CHILONZOR.getRu();
            case YUNUSOBOD:
                return District.YUNUSOBOD.getRu();
            case YAKKASAROY:
                return District.YAKKASAROY.getRu();
            case BEKOBOD:
                return District.BEKOBOD.getRu();
            case BOSTONLIQ:
                return District.BOSTONLIQ.getRu();
            case BOKA:
                return District.BOKA.getRu();
            case CHINOZ:
                return District.CHINOZ.getRu();
            case QIBRAY:
                return District.QIBRAY.getRu();
            case OHANGARON:
                return District.OHANGARON.getRu();
            case OQQORGON:
                return District.OQQORGON.getRu();
            case PARKENT:
                return District.PARKENT.getRu();
            case PISKENT:
                return District.PISKENT.getRu();
            case QUYI_CHIRCHIQ:
                return District.QUYI_CHIRCHIQ.getRu();
            case ZANGIOTA:
                return District.ZANGIOTA.getRu();
            case ORTA_CHIRCHIQ:
                return District.ORTA_CHIRCHIQ.getRu();
            case YANGIYOL:
                return District.YANGIYOL.getRu();
            case YUQORI_CHIRCHIQ:
                return District.YUQORI_CHIRCHIQ.getRu();
            case SHAHRIXON:
                return District.SHAHRIXON.getRu();
            case ASAKA:
                return District.ASAKA.getRu();
            case QORGONTEPA:
                return District.QORGONTEPA.getRu();
            case ANDIJON:
                return District.ANDIJON.getRu();
            case BALIQCHI:
                return District.BALIQCHI.getRu();
            case OLTINKOL:
                return District.OLTINKOL.getRu();
            case JALAQUDUQ:
                return District.JALAQUDUQ.getRu();
            case IZBOSKAN:
                return District.IZBOSKAN.getRu();
            case PAXTAOBOD:
                return District.PAXTAOBOD.getRu();
            case MARHAMAT:
                return District.MARHAMAT.getRu();
            case XOJAOBOD:
                return District.XOJAOBOD.getRu();
            case BULOQBOSHI:
                return District.BULOQBOSHI.getRu();
            case BOSTON:
                return District.BOSTON.getRu();
            case ULUGNOR:
                return District.ULUGNOR.getRu();
            case XONOBOD:
                return District.XONOBOD.getRu();
            case BUXORO:
                return District.BUXORO.getRu();
            case GIJDUVON:
                return District.GIJDUVON.getRu();
            case JONDOR:
                return District.JONDOR.getRu();
            case KOGON:
                return District.KOGON.getRu();
            case OLOT:
                return District.OLOT.getRu();
            case PESHKU:
                return District.PESHKU.getRu();
            case QORAKOL:
                return District.QORAKOL.getRu();
            case QOROVULBOZOR:
                return District.QOROVULBOZOR.getRu();
            case ROMITAN:
                return District.ROMITAN.getRu();
            case SHOFIRKON:
                return District.SHOFIRKON.getRu();
            case VOBKENT:
                return District.VOBKENT.getRu();
            case ARNASOY:
                return District.ARNASOY.getRu();
            case BAXMAL:
                return District.BAXMAL.getRu();
            case DOSTLIK:
                return District.DOSTLIK.getRu();
            case FORISH:
                return District.FORISH.getRu();
            case GALLAOROL:
                return District.GALLAOROL.getRu();
            case JIZZAX:
                return District.JIZZAX.getRu();
            case MIRZACHOL:
                return District.MIRZACHOL.getRu();
            case PAXTAKOR:
                return District.PAXTAKOR.getRu();
            case YANGIOBOD:
                return District.YANGIOBOD.getRu();
            case ZAFAROBOD:
                return District.ZAFAROBOD.getRu();
            case ZARBAND:
                return District.ZARBAND.getRu();
            case ZOMIN:
                return District.ZOMIN.getRu();
            case CHIROQCHI:
                return District.CHIROQCHI.getRu();
            case DEHQONOBOD:
                return District.DEHQONOBOD.getRu();
            case GUZOR:
                return District.GUZOR.getRu();
            case KASBI:
                return District.KASBI.getRu();
            case KITOB:
                return District.KITOB.getRu();
            case KOSON:
                return District.KOSON.getRu();
            case MIRISHKOR:
                return District.MIRISHKOR.getRu();
            case MUBORAK:
                return District.MUBORAK.getRu();
            case NISHON:
                return District.NISHON.getRu();
            case QAMASHI:
                return District.QAMASHI.getRu();
            case QARSHI:
                return District.QARSHI.getRu();
            case SHAHRISABZ:
                return District.SHAHRISABZ.getRu();
            case YAKKABOG:
                return District.YAKKABOG.getRu();
            case KARMANA:
                return District.KARMANA.getRu();
            case KONIMEX:
                return District.KONIMEX.getRu();
            case NAVBAHOR:
                return District.NAVBAHOR.getRu();
            case NUROTA:
                return District.NUROTA.getRu();
            case QIZILTEPA:
                return District.QIZILTEPA.getRu();
            case TOMDI:
                return District.TOMDI.getRu();
            case UCHQUDUQ:
                return District.UCHQUDUQ.getRu();
            case XATIRCHI:
                return District.XATIRCHI.getRu();
            case CHORTOQ:
                return District.CHORTOQ.getRu();
            case CHUST:
                return District.CHUST.getRu();
            case KOSONSOY:
                return District.KOSONSOY.getRu();
            case MINGBULOQ:
                return District.MINGBULOQ.getRu();
            case NAMANGON:
                return District.NAMANGON.getRu();
            case NORIN:
                return District.NORIN.getRu();
            case POP:
                return District.POP.getRu();
            case TORAQORGON:
                return District.TORAQORGON.getRu();
            case UCHQORGON:
                return District.UCHQORGON.getRu();
            case UYCHI:
                return District.UYCHI.getRu();
            case YANGIQORGON:
                return District.YANGIQORGON.getRu();
            case BULUNGUR:
                return District.BULUNGUR.getRu();
            case ISHTIXON:
                return District.ISHTIXON.getRu();
            case JOMBOY:
                return District.JOMBOY.getRu();
            case KATTAQORGON:
                return District.KATTAQORGON.getRu();
            case NARPAY:
                return District.NARPAY.getRu();
            case NUROBOD:
                return District.NUROBOD.getRu();
            case OQDARYO:
                return District.OQDARYO.getRu();
            case PAST_DARGOM:
                return District.PAST_DARGOM.getRu();
            case PAXTACHI:
                return District.PAXTACHI.getRu();
            case POYARIQ:
                return District.POYARIQ.getRu();
            case QOSHRABOT:
                return District.QOSHRABOT.getRu();
            case SAMARQAND:
                return District.SAMARQAND.getRu();
            case TOYLOQ:
                return District.TOYLOQ.getRu();
            case URGUT:
                return District.URGUT.getRu();
            case ANGOR:
                return District.ANGOR.getRu();
            case BANDIXON:
                return District.BANDIXON.getRu();
            case BOYSUN:
                return District.BOYSUN.getRu();
            case DENOV:
                return District.DENOV.getRu();
            case JARQORGON:
                return District.JARQORGON.getRu();
            case MUZROBOR:
                return District.MUZROBOR.getRu();
            case OLTINSOY:
                return District.OLTINSOY.getRu();
            case QIZIRIQ:
                return District.QIZIRIQ.getRu();
            case QUMQORGON:
                return District.QUMQORGON.getRu();
            case SARIOSIYO:
                return District.SARIOSIYO.getRu();
            case SHEROBOD:
                return District.SHEROBOD.getRu();
            case SHORCHI:
                return District.SHORCHI.getRu();
            case TERMIZ:
                return District.TERMIZ.getRu();
            case UZUN:
                return District.UZUN.getRu();
            case BOYOVUT:
                return District.BOYOVUT.getRu();
            case GULISTON:
                return District.GULISTON.getRu();
            case OQOLTIN:
                return District.OQOLTIN.getRu();
            case SARDOBA:
                return District.SARDOBA.getRu();
            case SAYXUNOBOD:
                return District.SAYXUNOBOD.getRu();
            case SIRDARYO:
                return District.SIRDARYO.getRu();
            case XOVOS:
                return District.XOVOS.getRu();
            case MIRZAOBOD:
                return District.MIRZAOBOD.getRu();
            case BESHARIQ:
                return District.BESHARIQ.getRu();
            case BOGDOD:
                return District.BOGDOD.getRu();
            case BUVAYDA:
                return District.BUVAYDA.getRu();
            case DANGARA:
                return District.DANGARA.getRu();
            case FARGONA:
                return District.FARGONA.getRu();
            case FURQAT:
                return District.FURQAT.getRu();
            case OZBEKISTON:
                return District.OZBEKISTON.getRu();
            case OLTIARIQ:
                return District.OLTIARIQ.getRu();
            case QOSHTEPA:
                return District.QOSHTEPA.getRu();
            case QUVA:
                return District.QUVA.getRu();
            case RISHTON:
                return District.RISHTON.getRu();
            case SOX:
                return District.SOX.getRu();
            case TOSHLOQ:
                return District.TOSHLOQ.getRu();
            case UCHKOPRIK:
                return District.UCHKOPRIK.getRu();
            case YOZYOVON:
                return District.YOZYOVON.getRu();
            case BOGOT:
                return District.BOGOT.getRu();
            case GURLAN:
                return District.GURLAN.getRu();
            case QOSHKOPIR:
                return District.QOSHKOPIR.getRu();
            case SHOVOT:
                return District.SHOVOT.getRu();
            case URGANCH:
                return District.URGANCH.getRu();
            case XAZORASP:
                return District.XAZORASP.getRu();
            case XIVA:
                return District.XIVA.getRu();
            case XONQA:
                return District.XONQA.getRu();
            case YANGIARIQ:
                return District.YANGIARIQ.getRu();
            case YANGIBOZOR:
                return District.YANGIBOZOR.getRu();
            case AMUDARYO:
                return District.AMUDARYO.getRu();
            case BERUNIY:
                return District.BERUNIY.getRu();
            case CHIMBOY:
                return District.CHIMBOY.getRu();
            case ELLIKQALA:
                return District.ELLIKQALA.getRu();
            case KEGEYLI:
                return District.KEGEYLI.getRu();
            case MOYNOQ:
                return District.MOYNOQ.getRu();
            case NUKUS:
                return District.NUKUS.getRu();
            case QONLIKOL:
                return District.QONLIKOL.getRu();
            case QORAUZAQ:
                return District.QORAUZAQ.getRu();
            case QUNGIROT:
                return District.QUNGIROT.getRu();
            case SHUMANAY:
                return District.SHUMANAY.getRu();
            case TAXTAKOPIR:
                return District.TAXTAKOPIR.getRu();
            case TORTKOL:
                return District.TORTKOL.getRu();
            case XOJAYLI:
                return District.XOJAYLI.getRu();

        }
        return ERROR;
    }


    private static String getEnWord(String word) {
        switch (word) {
            case UZ:
                return UZ;
            case RU:
                return RU;
            case EN:
                return EN;
            case ADMIN_USERS_SHOW_MENU_TEXT:
                return ADMIN_USERS_SHOW_MENU_TEXT;
            case ADMIN_CHOOSE_USERS_MENU_TEXT:
                return ADMIN_CHOOSE_USERS_MENU_TEXT;
            case ADMIN_ENTER_PHONE_NUMBER_MENU_TEXT:
                return ADMIN_ENTER_PHONE_NUMBER_MENU_TEXT;
            case ADMIN_SHOW_USERS:
                return ADMIN_SHOW_USERS;
            case ADMIN_SHOW_HOMES:
                return ADMIN_SHOW_HOMES;
            case ADMIN_EXCEL_FILE:
                return ADMIN_EXCEL_FILE;
            case ADMIN_ACTIVE_USERS:
                return ADMIN_ACTIVE_USERS;
            case ADMIN_DEACTIVATED_USERS:
                return ADMIN_DEACTIVATED_USERS;
            case ADMIN_USER_INFO_PHONE_NUMBER:
                return ADMIN_USER_INFO_PHONE_NUMBER;
            case ADMIN_USER_INFO_NAME:
                return ADMIN_USER_INFO_NAME;
            case ADMIN_USER_INFO_LANGUAGE:
                return ADMIN_USER_INFO_LANGUAGE;
            case ADMIN_HOMES_IN_WEEK:
                return ADMIN_HOMES_IN_WEEK;
            case ADMIN_HOMES_IN_DAY:
                return ADMIN_HOMES_IN_DAY;
            case ADMIN_HOMES_INFO_HOME_TYPE:
                return ADMIN_HOMES_INFO_HOME_TYPE;
            case ADMIN_HOMES_INFO_REGION:
                return ADMIN_HOMES_INFO_REGION;
            case ADMIN_HOMES_INFO_DISTRICT:
                return ADMIN_HOMES_INFO_DISTRICT;
            case ADMIN_HOMES_INFO_ADDRESS:
                return ADMIN_HOMES_INFO_ADDRESS;
            case ADMIN_HOMES_INFO_NUMBER_OF_ROOMS:
                return ADMIN_HOMES_INFO_NUMBER_OF_ROOMS;
            case ADMIN_HOMES_INFO_AREA:
                return ADMIN_HOMES_INFO_AREA;
            case ADMIN_HOMES_INFO_DESCRIPTION:
                return ADMIN_HOMES_INFO_DESCRIPTION;
            case ADMIN_HOMES_INFO_NUMBER_OF_INTERESTED:
                return ADMIN_HOMES_INFO_NUMBER_OF_INTERESTED;
            case ADMIN_HOMES_INFO_MAP_URL:
                return ADMIN_HOMES_INFO_MAP_URL;
            case ADMIN_HOMES_FILTER_MENU_TEXT:
                return ADMIN_HOMES_FILTER_MENU_TEXT;


            case CHOOSE_ACTION:
                return CHOOSE_ACTION;
            case CHOOSE_LANGUAGE_MENU_TEXT:
                return CHOOSE_LANGUAGE_MENU_TEXT;
            case CHOOSE_REGION_MENU_TEXT:
                return CHOOSE_REGION_MENU_TEXT;
            case SET_ACCOMMODATION_FOR_MENU_TEXT:
                return SET_ACCOMMODATION_FOR_MENU_TEXT;
            case CHOOSE_ACCOMMODATION_TYPE_MENU_TEXT:
                return CHOOSE_ACCOMMODATION_TYPE_MENU_TEXT;
            case ENTER_MAX_VALUE_MENU_TEXT:
                return ENTER_MAX_VALUE_MENU_TEXT;
            case ENTER_MIN_VALUE_MENU_TEXT:
                return ENTER_MIN_VALUE_MENU_TEXT;
            case ENTER_AREA_MENU_TEXT:
                return ENTER_AREA_MENU_TEXT;
            case SEND_PHOTO_MENU_TEXT:
                return SEND_PHOTO_MENU_TEXT;
            case ENTER_PRICE_MENU_TEXT:
                return ENTER_PRICE_MENU_TEXT;
            case WRITE_DESCRIPTION_MENU_TEXT:
                return WRITE_DESCRIPTION_MENU_TEXT;
            case CHANGE_LANGUAGE:
                return CHANGE_LANGUAGE;
            case WELCOME_TEXT:
                return WELCOME_TEXT;
            case SEARCH:
                return SEARCH;
            case BACK:
                return BACK;
            case FOR_RENTING:
                return FOR_RENTING;
            case FOR_SELLING:
                return FOR_SELLING;
            case WRITE_ADDRESS:
                return WRITE_ADDRESS;
            case SEND_LOCATION:
                return SEND_LOCATION;
            case HOUSE:
                return HOUSE;
            case FLAT:
                return FLAT;
            case NUMBER_OF_ROOMS:
                return NUMBER_OF_ROOMS;
            case AREA:
                return AREA;
            case SEND_PHOTOS:
                return SEND_PHOTOS;
            case DO_NOT_SEND_PHOTO:
                return DO_NOT_SEND_PHOTO;
            case SET_PRICE:
                return SET_PRICE;
            case WRITE_DESCRIPTION:
                return WRITE_DESCRIPTION;
            case HOUSE_TYPE:
                return HOUSE_TYPE;
            case ADDRESS:
                return ADDRESS;
            case DESCRIPTION:
                return DESCRIPTION;
            case DATE:
                return DATE;
            case NUMBER_OF_LIKES:
                return NUMBER_OF_LIKES;
            case NUMBER_OF_VIEWS:
                return NUMBER_OF_VIEWS;
            case GET_PHONE_NUMBER:
                return GET_PHONE_NUMBER;
            case MY_ACCOMMODATIONS:
                return MY_ACCOMMODATIONS;
            case MY_FAVOURITES:
                return MY_FAVOURITES;
            case SEARCH_BY_ROOMS:
                return SEARCH_BY_ROOMS;
            case SEARCH_BY_PRICE:
                return SEARCH_BY_PRICE;
            case MAX_PRICE:
                return MAX_PRICE;
            case MIN_PRICE:
                return MIN_PRICE;
            case MAX_ROOMS:
                return MAX_ROOMS;
            case MIN_ROOMS:
                return MIN_ROOMS;
            case ENTER_PHONE_NUMBER_TEXT:
                return ENTER_PHONE_NUMBER_TEXT;
            case SEND_PHONE_NUMBER:
                return SEND_PHONE_NUMBER;
            case CHANGE_LANGUAGE_TEXT:
                return CHANGE_LANGUAGE_TEXT;
            case ADD_ACCOMMODATION:
                return ADD_ACCOMMODATION;
            case SHOW_ACCOMMODATIONS:
                return SHOW_ACCOMMODATIONS;
            case MY_NOTES:
                return MY_NOTES;
            case SETTINGS:
                return SETTINGS;
            case MENU_TEXT:
                return MENU_TEXT;
            case REGISTRATION:
                return REGISTRATION;
            case CHOOSE_ONE:
                return CHOOSE_ONE;
            case MY_PHONE_NUMBER:
                return MY_PHONE_NUMBER;
            case REGISTER_WARNING_TEXT:
                return REGISTER_WARNING_TEXT;
            case WRITE_SEND_LOCATION_TEXT:
                return WRITE_SEND_LOCATION_TEXT;
            case SEND_LOCATION_TEXT:
                return SEND_LOCATION_TEXT;
            case LOCATION_NOT_FOUND:
                return LOCATION_NOT_FOUND;
            case SUCCESSFULLY_SAVED:
                return SUCCESSFULLY_SAVED;
            case SHOW_ALL:
                return SHOW_ALL;
            case ADMIN_HOMES_INFO_PRICE:
                return ADMIN_HOMES_INFO_PRICE;
            case HOMES_NOT_FOUND:
                return HOMES_NOT_FOUND;
            case GET_RENTING:
                return GET_RENTING;
            case FOR_BUY:
                return FOR_BUY;
            case SKIP:
                return SKIP;
            case STATUS:
                return STATUS;
            case RENT:
                return RENT;
            case SELL:
                return SELL;
            case MENU:
                return MENU;
            case ADMIN:
                return ADMIN;
            case USER:
                return USER;
            case ADMIN_USER_INFO_USERNAME:
                return ADMIN_USER_INFO_USERNAME;
            case ROLE:
                return ROLE;
            case SITUATION:
                return SITUATION;
            case ACTIVE:
                return ACTIVE;
            case DE_ACTIVE:
                return DE_ACTIVE;
            case CHECK_USER_BY_ADMIN_TEXT:
                return CHECK_USER_BY_ADMIN_TEXT;
            case NEXT_ACTION:return NEXT_ACTION;
            case HOME_PHOTOS:return HOME_PHOTOS;
            case IT_HAS_ONLY_ONE_PIC:return IT_HAS_ONLY_ONE_PIC;
            case FIRST_PAGE_NOTIFICATION:return FIRST_PAGE_NOTIFICATION;
            case LAST_PAGE_NOTIFICATION:return LAST_PAGE_NOTIFICATION;

            case TASHKENT:
                return Region.TASHKENT.getEng();
            case TASHKENT_REGION:
                return Region.TASHKENT_REGION.getEng();
            case ANDIJAN:
                return Region.ANDIJAN.getEng();
            case BUKHARA:
                return Region.BUKHARA.getEng();
            case DZHIZAK:
                return Region.DZHIZAK.getEng();
            case KASHKADARYA:
                return Region.KASHKADARYA.getEng();
            case NAVOI:
                return Region.NAVOI.getEng();
            case NAMANGAN:
                return Region.NAMANGAN.getEng();
            case SAMARKAND:
                return Region.SAMARKAND.getEng();
            case SURKHANDARYA:
                return Region.SURKHANDARYA.getEng();
            case SYRDARYA:
                return Region.SYRDARYA.getEng();
            case FERGHANA:
                return Region.FERGHANA.getEng();
            case XORAZM:
                return Region.XORAZM.getEng();
            case REPUBLIC_OF_KARAKALPAKSTAN:
                return Region.REPUBLIC_OF_KARAKALPAKSTAN.getEng();
            case CHOOSE_DISTRICT_MENU_TEXT:
                return CHOOSE_DISTRICT_MENU_TEXT;
            case BAN_MENU_TEXT:return BAN_MENU_TEXT;

            case OLMAZOR:
                return District.OLMAZOR.getEng();
            case BEKTEMIR:
                return District.BEKTEMIR.getEng();
            case MIROBOD:
                return District.MIROBOD.getEng();
            case MIRZO_ULUGBEK:
                return District.MIRZO_ULUGBEK.getEng();
            case SERGELI:
                return District.SERGELI.getEng();
            case UCHTEPA:
                return District.UCHTEPA.getEng();
            case SHAYXONTOHUR:
                return District.SHAYXONTOHUR.getEng();
            case YASHNOBOD:
                return District.YASHNOBOD.getEng();
            case CHILONZOR:
                return District.CHILONZOR.getEng();
            case YUNUSOBOD:
                return District.YUNUSOBOD.getEng();
            case YAKKASAROY:
                return District.YAKKASAROY.getEng();
            case BEKOBOD:
                return District.BEKOBOD.getEng();
            case BOSTONLIQ:
                return District.BOSTONLIQ.getEng();
            case BOKA:
                return District.BOKA.getEng();
            case CHINOZ:
                return District.CHINOZ.getEng();
            case QIBRAY:
                return District.QIBRAY.getEng();
            case OHANGARON:
                return District.OHANGARON.getEng();
            case OQQORGON:
                return District.OQQORGON.getEng();
            case PARKENT:
                return District.PARKENT.getEng();
            case PISKENT:
                return District.PISKENT.getEng();
            case QUYI_CHIRCHIQ:
                return District.QUYI_CHIRCHIQ.getEng();
            case ZANGIOTA:
                return District.ZANGIOTA.getEng();
            case ORTA_CHIRCHIQ:
                return District.ORTA_CHIRCHIQ.getEng();
            case YANGIYOL:
                return District.YANGIYOL.getEng();
            case YUQORI_CHIRCHIQ:
                return District.YUQORI_CHIRCHIQ.getEng();
            case SHAHRIXON:
                return District.SHAHRIXON.getEng();
            case ASAKA:
                return District.ASAKA.getEng();
            case QORGONTEPA:
                return District.QORGONTEPA.getEng();
            case ANDIJON:
                return District.ANDIJON.getEng();
            case BALIQCHI:
                return District.BALIQCHI.getEng();
            case OLTINKOL:
                return District.OLTINKOL.getEng();
            case JALAQUDUQ:
                return District.JALAQUDUQ.getEng();
            case IZBOSKAN:
                return District.IZBOSKAN.getEng();
            case PAXTAOBOD:
                return District.PAXTAOBOD.getEng();
            case MARHAMAT:
                return District.MARHAMAT.getEng();
            case XOJAOBOD:
                return District.XOJAOBOD.getEng();
            case BULOQBOSHI:
                return District.BULOQBOSHI.getEng();
            case BOSTON:
                return District.BOSTON.getEng();
            case ULUGNOR:
                return District.ULUGNOR.getEng();
            case XONOBOD:
                return District.XONOBOD.getEng();
            case BUXORO:
                return District.BUXORO.getEng();
            case GIJDUVON:
                return District.GIJDUVON.getEng();
            case JONDOR:
                return District.JONDOR.getEng();
            case KOGON:
                return District.KOGON.getEng();
            case OLOT:
                return District.OLOT.getEng();
            case PESHKU:
                return District.PESHKU.getEng();
            case QORAKOL:
                return District.QORAKOL.getEng();
            case QOROVULBOZOR:
                return District.QOROVULBOZOR.getEng();
            case ROMITAN:
                return District.ROMITAN.getEng();
            case SHOFIRKON:
                return District.SHOFIRKON.getEng();
            case VOBKENT:
                return District.VOBKENT.getEng();
            case ARNASOY:
                return District.ARNASOY.getEng();
            case BAXMAL:
                return District.BAXMAL.getEng();
            case DOSTLIK:
                return District.DOSTLIK.getEng();
            case FORISH:
                return District.FORISH.getEng();
            case GALLAOROL:
                return District.GALLAOROL.getEng();
            case JIZZAX:
                return District.JIZZAX.getEng();
            case MIRZACHOL:
                return District.MIRZACHOL.getEng();
            case PAXTAKOR:
                return District.PAXTAKOR.getEng();
            case YANGIOBOD:
                return District.YANGIOBOD.getEng();
            case ZAFAROBOD:
                return District.ZAFAROBOD.getEng();
            case ZARBAND:
                return District.ZARBAND.getEng();
            case ZOMIN:
                return District.ZOMIN.getEng();
            case CHIROQCHI:
                return District.CHIROQCHI.getEng();
            case DEHQONOBOD:
                return District.DEHQONOBOD.getEng();
            case GUZOR:
                return District.GUZOR.getEng();
            case KASBI:
                return District.KASBI.getEng();
            case KITOB:
                return District.KITOB.getEng();
            case KOSON:
                return District.KOSON.getEng();
            case MIRISHKOR:
                return District.MIRISHKOR.getEng();
            case MUBORAK:
                return District.MUBORAK.getEng();
            case NISHON:
                return District.NISHON.getEng();
            case QAMASHI:
                return District.QAMASHI.getEng();
            case QARSHI:
                return District.QARSHI.getEng();
            case SHAHRISABZ:
                return District.SHAHRISABZ.getEng();
            case YAKKABOG:
                return District.YAKKABOG.getEng();
            case KARMANA:
                return District.KARMANA.getEng();
            case KONIMEX:
                return District.KONIMEX.getEng();
            case NAVBAHOR:
                return District.NAVBAHOR.getEng();
            case NUROTA:
                return District.NUROTA.getEng();
            case QIZILTEPA:
                return District.QIZILTEPA.getEng();
            case TOMDI:
                return District.TOMDI.getEng();
            case UCHQUDUQ:
                return District.UCHQUDUQ.getEng();
            case XATIRCHI:
                return District.XATIRCHI.getEng();
            case CHORTOQ:
                return District.CHORTOQ.getEng();
            case CHUST:
                return District.CHUST.getEng();
            case KOSONSOY:
                return District.KOSONSOY.getEng();
            case MINGBULOQ:
                return District.MINGBULOQ.getEng();
            case NAMANGON:
                return District.NAMANGON.getEng();
            case NORIN:
                return District.NORIN.getEng();
            case POP:
                return District.POP.getEng();
            case TORAQORGON:
                return District.TORAQORGON.getEng();
            case UCHQORGON:
                return District.UCHQORGON.getEng();
            case UYCHI:
                return District.UYCHI.getEng();
            case YANGIQORGON:
                return District.YANGIQORGON.getEng();
            case BULUNGUR:
                return District.BULUNGUR.getEng();
            case ISHTIXON:
                return District.ISHTIXON.getEng();
            case JOMBOY:
                return District.JOMBOY.getEng();
            case KATTAQORGON:
                return District.KATTAQORGON.getEng();
            case NARPAY:
                return District.NARPAY.getEng();
            case NUROBOD:
                return District.NUROBOD.getEng();
            case OQDARYO:
                return District.OQDARYO.getEng();
            case PAST_DARGOM:
                return District.PAST_DARGOM.getEng();
            case PAXTACHI:
                return District.PAXTACHI.getEng();
            case POYARIQ:
                return District.POYARIQ.getEng();
            case QOSHRABOT:
                return District.QOSHRABOT.getEng();
            case SAMARQAND:
                return District.SAMARQAND.getEng();
            case TOYLOQ:
                return District.TOYLOQ.getEng();
            case URGUT:
                return District.URGUT.getEng();
            case ANGOR:
                return District.ANGOR.getEng();
            case BANDIXON:
                return District.BANDIXON.getEng();
            case BOYSUN:
                return District.BOYSUN.getEng();
            case DENOV:
                return District.DENOV.getEng();
            case JARQORGON:
                return District.JARQORGON.getEng();
            case MUZROBOR:
                return District.MUZROBOR.getEng();
            case OLTINSOY:
                return District.OLTINSOY.getEng();
            case QIZIRIQ:
                return District.QIZIRIQ.getEng();
            case QUMQORGON:
                return District.QUMQORGON.getEng();
            case SARIOSIYO:
                return District.SARIOSIYO.getEng();
            case SHEROBOD:
                return District.SHEROBOD.getEng();
            case SHORCHI:
                return District.SHORCHI.getEng();
            case TERMIZ:
                return District.TERMIZ.getEng();
            case UZUN:
                return District.UZUN.getEng();
            case BOYOVUT:
                return District.BOYOVUT.getEng();
            case GULISTON:
                return District.GULISTON.getEng();
            case OQOLTIN:
                return District.OQOLTIN.getEng();
            case SARDOBA:
                return District.SARDOBA.getEng();
            case SAYXUNOBOD:
                return District.SAYXUNOBOD.getEng();
            case SIRDARYO:
                return District.SIRDARYO.getEng();
            case XOVOS:
                return District.XOVOS.getEng();
            case MIRZAOBOD:
                return District.MIRZAOBOD.getEng();
            case BESHARIQ:
                return District.BESHARIQ.getEng();
            case BOGDOD:
                return District.BOGDOD.getEng();
            case BUVAYDA:
                return District.BUVAYDA.getEng();
            case DANGARA:
                return District.DANGARA.getEng();
            case FARGONA:
                return District.FARGONA.getEng();
            case FURQAT:
                return District.FURQAT.getEng();
            case OZBEKISTON:
                return District.OZBEKISTON.getEng();
            case OLTIARIQ:
                return District.OLTIARIQ.getEng();
            case QOSHTEPA:
                return District.QOSHTEPA.getEng();
            case QUVA:
                return District.QUVA.getEng();
            case RISHTON:
                return District.RISHTON.getEng();
            case SOX:
                return District.SOX.getEng();
            case TOSHLOQ:
                return District.TOSHLOQ.getEng();
            case UCHKOPRIK:
                return District.UCHKOPRIK.getEng();
            case YOZYOVON:
                return District.YOZYOVON.getEng();
            case BOGOT:
                return District.BOGOT.getEng();
            case GURLAN:
                return District.GURLAN.getEng();
            case QOSHKOPIR:
                return District.QOSHKOPIR.getEng();
            case SHOVOT:
                return District.SHOVOT.getEng();
            case URGANCH:
                return District.URGANCH.getEng();
            case XAZORASP:
                return District.XAZORASP.getEng();
            case XIVA:
                return District.XIVA.getEng();
            case XONQA:
                return District.XONQA.getEng();
            case YANGIARIQ:
                return District.YANGIARIQ.getEng();
            case YANGIBOZOR:
                return District.YANGIBOZOR.getEng();
            case AMUDARYO:
                return District.AMUDARYO.getEng();
            case BERUNIY:
                return District.BERUNIY.getEng();
            case CHIMBOY:
                return District.CHIMBOY.getEng();
            case ELLIKQALA:
                return District.ELLIKQALA.getEng();
            case KEGEYLI:
                return District.KEGEYLI.getEng();
            case MOYNOQ:
                return District.MOYNOQ.getEng();
            case NUKUS:
                return District.NUKUS.getEng();
            case QONLIKOL:
                return District.QONLIKOL.getEng();
            case QORAUZAQ:
                return District.QORAUZAQ.getEng();
            case QUNGIROT:
                return District.QUNGIROT.getEng();
            case SHUMANAY:
                return District.SHUMANAY.getEng();
            case TAXTAKOPIR:
                return District.TAXTAKOPIR.getEng();
            case TORTKOL:
                return District.TORTKOL.getEng();
            case XOJAYLI:
                return District.XOJAYLI.getEng();

        }
        return ERROR;
    }
}
