package uz.pdp.rentseekerlongpolling.util.enums;

public enum BotState {
    // MAIN_MENU
    CHOOSE_LANGUAGE,
    ADMIN_MENU_SEND,
    CHECK_USER_BY_ADMIN,
    ADMIN_MENU_EDIT,
    ADMIN_PANEL,
    MAIN_MENU_SEND,
    MAIN_MENU_EDIT,
    // ADD HOME
    GIVE_HOME_STATUS,
    WRITE_OR_SEND_LOCATION,
    LOCATION_MENU,
    GIVE_REGION,
    GIVE_DISTRICT,
    GIVE_ADDRESS,
    GIVE_HOME_TYPE_EDIT,
    GIVE_HOME_TYPE_SEND,
    GIVE_HOME_NUMBER,
    GIVE_HOME_AREA_SEND,
    GIVE_HOME_AREA_EDIT,
    GIVE_HOME_PHOTO_SEND,
    GIVE_HOME_PHOTO_SEND_SIMPLE,
    GIVE_HOME_PHOTO_EDIT,
    GIVE_HOME_PHOTO_SEND_AGAIN,
    GIVE_HOME_PRICE_SEND,
    GIVE_HOME_PRICE_EDIT,
    GIVE_HOME_DESCRIPTION,
    SAVE_HOME_TO_STORE,
    // SHOW
    SHOW_MENU_EDIT,
    SHOW_MENU_SEND,
    CHOOSE_HOME_STATUS,
    CHOOSE_REGION,
    CHOOSE_DISTRICT,
    CHOOSE_HOME_TYPE,
    CHOOSE_HOME_NUMBER_EDIT,
    CHOOSE_HOME_NUMBER_SEND,
    CHOOSE_HOME_MIN_PRICE_SEND,
    CHOOSE_HOME_MIN_PRICE_EDIT,
    CHOOSE_HOME_MAX_PRICE_SEND,
    CHOOSE_HOME_MAX_PRICE_EDIT,
    SHOW_OPTIONS,
    GET_PHONE,
    SHOW_HOME_PHONE_MENU_ALL,
    SHOW_HOME_PHONE_MENU_SEARCH,
    SHOW_HOME_PHONE_MENU_FAVOURITES,
    SHOW_HOME_PHONE_MENU_MY_ACCOMMODATIONS,
    CHANGE_HOME_LIKE_MENU_ALL,
    CHANGE_HOME_LIKE_MENU_SEARCH,
    CHANGE_HOME_LIKE_MENU_FAVOURITES,
    CHANGE_HOME_LIKE_MENU_MY_ACCOMMODATIONS,
    DELETE_ACCOMMODATION,
    // SEARCH
    SEARCH_TYPE,
    GET_MIN_SEARCH,
    GET_MAX_SEARCH,
    SHOW_SORTED_OPTIONS,
    // MY NOTES
    MY_NOTES_MENU_SEND,
    MY_NOTES_MENU_EDIT,
    MY_HOMES,
    MY_FAVOURITES,
    // SETTINGS
    SETTINGS_MENU_EDIT,
    SETTINGS_MENU_SEND,
    CHANGE_LANGUAGE,
    REGISTER,
    SAVE_PHONE,
    SHOW_HOME_PHOTOS,


    ERROR,



















    //ADMIN

    //BOT_STATE
    ADMIN_MAIN_MENU_SEND,
    ADMIN_MAIN_MENU_EDIT,

    //SHOW USERS
    ADMIN_USERS_SHOW,

    //EXCEL FILE
    ADMIN_CHOOSE_USER_TYPE_SEND,
    ADMIN_CHOOSE_USER_TYPE_EDIT,
    ADMIN_GET_ACTIVE_EXCEL_FILE,
    ADMIN_GET_DEACTIVATED_EXCEL_FILE,

    //SEARCH
    ADMIN_USER_ENTER_PHONE_NUMBER_EDIT,
    ADMIN_USER_ENTER_PHONE_NUMBER_SEND,
    ADMIN_SEARCH_USER_INFO_SEND,
    ADMIN_SEARCH_USER_INFO_EDIT,


    //SHOW HOMES
    ADMIN_HOMES_FILTER_SEND,
    ADMIN_HOMES_FILTER_EDIT,
    ADMIN_DAY_HOMES_INFO,
    ADMIN_WEEK_HOMES_INFO,
    ADMIN_HOMES_INFO,
    ADMIN_HOMES_INFO_EDIT;
}
